### ISSUE TITLE
Cannot add platform to new capacitor project in nx with instructions from dev.to blog

### ISSUE THREAD

**Issue by wfairclough** [nxtend-team/nxtend#170]
![image](https://user-images.githubusercontent.com/1356641/86592901-45626d00-bf62-11ea-8fc4-4a30a22fba64.png)

```
$ npm version
{ npm: '6.14.5',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.9.3',
  icu: '64.2',
  modules: '64',
  napi: '6',
  nghttp2: '1.39.2',
  node: '10.20.1',
  openssl: '1.1.1e',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.34.2',
  v8: '6.8.275.32-node.56',
  zlib: '1.2.11' }

$ uname -a
Linux Orion 5.4.0-39-generic #43-Ubuntu SMP Fri Jun 19 10:28:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by wfairclough** [comment]
Hold on it seems to just be a documentation issues. I was able to get the platform to add by running the command like this:
`npx ng run app-native:add --platform android`

So it looks like the info in the blog is incorrect: https://dev.to/devinshoemaker/build-cross-platform-applications-in-a-monorepo-with-nx-ionic-and-capacitor-6f8

![image](https://user-images.githubusercontent.com/1356641/86593775-dab23100-bf63-11ea-9e7b-c28b11a100d8.png)

**Comment by devinshoemaker** [comment]
Hey! Thanks for catching this! The API changed a couple of times during development, I'll get the blog updated!

**Comment by devinshoemaker** [comment]
And done 😄  @wfairclough would you mind taking a look and then closing this issue?

**Comment by wfairclough** [comment]
Looks good now :100:

**Comment by devinshoemaker** [comment]
Awesome, thanks again!
