### ISSUE TITLE
@nxtend/capacitor: Capacitor and Cordova plugins are not being installed

### ISSUE THREAD

**Issue by mahnuh** [nxtend-team/nxtend#174]
I followed the docs and at foirst clance everything works finde. But I noticed plugins (Cordova and Capacitore are not being installed when running `nx run my-app:sync --platform ios`.

I think it is becaus you needed to add a nearly empty package.json to the app directory as the Capacitor CLI would crash otherwise. So this package.json does not have any dependencies and that is why the Capacitor CLI does not find any plugins to install.

I verified my theory by also adding my app's dependencies to the package.json in the app directory and then running `nx run my-app:sync --platform ios`. The result: all plugins are being found and installed.

Any ideas how not to have to add plugin dependencies in two different locations?

**Comment by devinshoemaker** [comment]
Do you have a repo with a reproduction of this?

Sadly, since I'm just tapping into the Capacitor CLI, this may require upstream changes to that project. Worst case scenario, I am betting you could use peer dependencies with a version of `*` and so you at least wouldn't have to maintain two copies of the version for each dependency, just the name of the dependency itself.

**Comment by mahnuh** [comment]
@devinshoemaker as I do not see any other solution at the moment I wrote a script that copies the root package.json to the app before any Capacitor cli commands and deletes it afterwards. So I don‘t have to maintain two package.json files.
This also might be a solution for your Capacitor plugin.

**Comment by devinshoemaker** [comment]
Hmm I will think about it. If I can't find another solution then I may add a schematic like `add-plugin` that adds the dependency to both `package.json` files. If you're copying your root `package.json` then don't you end up with two `node_modules/` directories?

**Comment by mahnuh** [comment]
@devinshoemaker I remove the duplicate `package.json` right after the Capacitor command, so I do not have multiple `node_modules`. Capacitor's `open` command does not need a `package.json` present. Not using @nxted/capacitor at the moment, my scripts look like this:

```
"scripts": {
    ...
    "pckgjsn:copy": "cp package.json apps/client/package.json",
    "pckgjsn:remove": "rm -rf apps/client/package.json",
    "copy:ios": "npm run pckgjsn:copy && (cd apps/client && npx cap copy ios) && npm run pckgjsn:remove",
    "sync:ios": "npm run pckgjsn:copy && (cd apps/client && npx cap sync ios) && npm run pckgjsn:remove",
    "open:ios": "(cd apps/client && npx cap open ios)",
    "start:ios": "npm run pckgjsn:copy && (cd apps/client && ionic capacitor run ios -l --external) && npm run pckgjsn:remove",
    ...
}
```

**Comment by paulantoine2** [comment]
Using @nxtend/capacitor :
```
"scripts": {
    ...
    "pckgjsn:copy": "cp package.json apps/mobile-cap/package.json",
    "pckgjsn:remove": "rm -rf apps/mobile-cap/package.json",
    "sync:ios": "npm run pckgjsn:copy && nx run mobile-cap:sync --platform ios && npm run pckgjsn:remove",
    "copy:ios": "npm run pckgjsn:copy && nx run mobile-cap:copy --platform ios && npm run pckgjsn:remove",
    ...
}
```

**Comment by devinshoemaker** [comment]
Thanks @mahnuh and @paulantoine2. Sorry for the late response, the last couple weeks have been incredibly busy for me. I plan on experimenting with this as a solution built into the plugin, and will also look at the Capacitor source code to see if I can make a PR to better handle this in general.

**Comment by devinshoemaker** [comment]
@mahnuh @paulantoine2 `@nxtend/capacitor` 1.1.0-beta.1 is available. Feel free to test it out and let me know how it works for you.

**Comment by devinshoemaker** [comment]
@nxtend/capacitor 1.1.0 has been released which should resolve this issue and remove the need for your custom `package.json` scripts. Thanks for the help!
