### ISSUE TITLE
Cannot read property 'types' of undefined

### ISSUE THREAD

**Issue by jafaircl** [nxtend-team/nxtend#193]
Running the following commands to set up a workspace/app results in a "Cannot read property 'types' of undefined" error after choosing any option for "Which stylesheet format would you like to use?":

```sh
npx create-nx-workspace@latest some-workspace
cd some-workspace
npm install --save-dev @nrwl/react @nxtend/ionic-react@latest
nx generate @nxtend/ionic-react:init
nx generate @nxtend/ionic-react:application some-app
```

The only references to any type properties are [here](https://github.com/nxtend-team/nxtend/blob/307bbcb2fa46284a7ae358ea44f5b8b78a1c1ec6/packages/ionic-react/src/schematics/application/lib/cypress.ts#L17) and [here](https://github.com/nxtend-team/nxtend/blob/cc6b91e23bdcbcd798ea4bfa0d2bc7f62390710b/packages/ionic-react/src/schematics/application/schematic.spec.ts#L389). Am I missing a step or is this an issue with the schematics?

**Comment by devinshoemaker** [comment]
I believe that this was actually an issue that was fixed with the last release due to some changes in Nx 10. If you update `@nxtend/ionic-react` and try to generate an application again then it should work. Let me know if you still have issues.

**Comment by jafaircl** [comment]
The new release does work and I'm not seeing the issue anymore. Thanks for your help!

**Comment by devinshoemaker** [comment]
No worries, I appreciate you reaching out with the issue!
