### ISSUE TITLE
ionic-angular

### ISSUE THREAD

**Issue by ntziolis** [nxtend-team/nxtend#210]
There are now a few folk on board for building nx-ionic-angular [support](https://github.com/nrwl/nx/issues/2633#issuecomment-672993877). 

I was about to create a new repo, but before doing so I wanted to check with you guys if you are open to add ionic-angular support within your repo. I feel there is lots of overlap and this way all ionic stuff would be in one location.

We could start building in a fork of your repo. After we get to a certain stage you guys could asses if you want to add it to the main repo. What do you think?

**Comment by devinshoemaker** [comment]
Hey there @ntziolis, thanks for the feedback. I plan to add an `ionic-angular` plugin to this workspace in the near future. Now that I have had a good amount of experience with the `ionic-react` plugin, I believe that I can get the Angular equivalent running pretty quickly. I expect to have a beta ready within a couple weeks, and when I do I can let you know. That being said, feel free to work on a plugin of your own if you'd like, I won't be offended at all.

**Comment by ntziolis** [comment]
That sounds perfect. I just added you to a private gitter channel. Not sure if you have the bandwidth to give some pointers but obviously having done the react piece your input would be invaluable

**Comment by ntziolis** [comment]
Obviously any other channel would be fine with me as well just name your poison :)

**Comment by devinshoemaker** [comment]
The best place to get this kind of help from me and other plugin authors would be the [Nrwl community Slack server](https://join.slack.com/t/nrwlcommunity/shared_invite/zt-ffstv0dy-wM2b~sYa_X7R8wXN02l2kA). I try to pop in and out of there when I have time, and there are a lot of other smart people that are more than willing to help out.

**Comment by luchillo17** [comment]
@devinshoemaker Have you taken a look at the issue @ntziolis linked? my team wants an Ionic-Angular monorepo project as well so I would like to contribute to this:
https://github.com/nrwl/nx/issues/2633

**Comment by devinshoemaker** [comment]
@luchillo17 sorry for the late reply. I have looked at that yes. I have been really busy lately but have a good idea of how to implement an Ionic Angular plugin. Once I get an initial release out, or even a beta, I'll be more than happy to take contributions. I'll be sure to comment on this issue once I get to that point.

**Comment by ntziolis** [comment]
High guys sry for the radio silence but the timeline one the project we wanted to use this for was moved up significantly and there was no time to spend on getting a nx plugin up and running before working on it sadly. I'm still available to contribute on any work necessary to make this happen though.

**Comment by devinshoemaker** [comment]
I've got the Angular plugin started, but sadly, similar story from me. This is a nights and weekends project for me and I've recently changed jobs and am moving so that time has been cut into. I'll definitely post on here when a beta is available.

**Comment by ntziolis** [comment]
Any chance to add me as a contributor, don't care at all if the repo is messy right now we all know it is.

**Comment by devinshoemaker** [comment]
I likely won't take contributions on the Angular plugin until I have at least a beta ready. But in general, you can fork this repo and create a PR if you'd like to make contributions.

**Comment by devinshoemaker** [comment]
Just wanted to give an update on this. Ionic Angular has been delayed due to some fundamental changes that I'm making to the Ionic React and Capacitor plugins that will require major releases. I plan to pick Ionic Angular back up once that is complete.

**Comment by Sina7312** [comment]
@devinshoemaker really exited to see this in action. We will wait for it :)

**Comment by devinshoemaker** [comment]
Initial Ionic Angular support has been released. Thanks for everyone's patience.

https://nxtend.dev/blog/ionic-angular-1.0.0
