### ISSUE TITLE
Project name already exists and Capacitor could not find the web assets directory 

### ISSUE THREAD

**Issue by curiouscod3** [nxtend-team/nxtend#247]
I followed the guide doc: https://nxtend.dev/docs/capacitor/getting-started/

After 'nx generate @nxtend/capacitor:capacitor-project ionic-react-cap --project ionic-react' ,

**I got this error : Project name already exists.**
The Ionic Project name is 'ionic-react' and 'ionic-react-cap'.

It happens again even if I changed the app name. 

```
❯ nx generate @nxtend/capacitor:init
❯ nx generate @nxtend/capacitor:capacitor-project ionic-react-cap --project ionic-react
? What app ID would you like to use? io.ionic.starter
? What app name would you like to use? 
Project name already exists.
```

So, What is wrong?

If I generate with --capacitor true, doesn't need to run that command?
```nx generate @nxtend/ionic-react:application ionic-react --capacitor true```

I am setting up Xplat Ionic/angular as well with nxtend ionic/react.

**Comment by curiouscod3** [comment]
I recreated without --capacitor true option.

and when I tried this command.

```
> nx run ionic-react-cap:add --platform=android 
[error] Capacitor could not find the web assets directory 
"~/dev/workspace/Projects/TotalProjects/NX-Lab/nx-base/dist/apps/ionic-react".
    Please create it and make sure it has an index.html file. You can change
    the path of this directory in capacitor.config.json (webDir option).
    You may need to compile the web assets for your app (typically 'npm run build').
    More info: https://capacitorjs.com/docs/basics/building-your-app
```
my `capacitor.config.json`

```
{
  "appId": "io.ionic.starter",
  "appName": "ionic-react",
  "bundledWebRuntime": false,
  "npmClient": "npm",
  "webDir": "../../dist/apps/ionic-react",
  "plugins": {
    "SplashScreen": {
      "launchShowDuration": 0
    }
  },
  "cordova": {}
}
```

**Comment by devinshoemaker** [comment]
Hey, thanks for reporting this! Is this repo public so that I could take a look? Also, how did you generate the `ionic-react` app you're referring to in your commands? Was it with the `@nxtend/ionic-react` plugin or Xplat?

**Comment by curiouscod3** [comment]
@devinshoemaker  
I've created NX Monorepo with NX, Xplat and nxtend.
Check this out! 
https://github.com/fullstackship/ultimate-nx-monorepo

**Comment by devinshoemaker** [comment]
So I see that you have an `ionic-react-cap` app already. Did you end up getting the Capacitor plugin working? 

Sweet repo though, I'll dive deeper when I have some more time.

I'm also working on an Ionic Angular plugin that I hope to have out in a few weeks. Life has been a bit unpredictable now though, so we will see how fast I can crank it out. 😄

**Comment by curiouscod3** [comment]
@devinshoemaker  I will try the plugins and if something wrong, I will tell you. Thank you :)  If ionic/angular done, I will add it on the repo as well  😄

**Comment by devinshoemaker** [comment]
The docs have been updated to let the user know to build their project before using native platforms. This should be rolled out with v2.
