### ISSUE TITLE
Unable to sync Capacitor project - Windows

### ISSUE THREAD

**Issue by sdunnin** [nxtend-team/nxtend#252]
My team is working with Capacitor and currently developing and testing with an Android build using the @nxtend/capacitor plugin. The developer that has it working is using MacOS. After a successful build on my Windows machine I get the following error from the sync command:
```
$ nx run controller-cap:sync --platform android

> ng run controller-cap:sync --platform=android 
C:\git\ONE\nevco-one\node_modules\.bin\cap:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
error Command failed with exit code 1.
```
Thinking that this could be a platform compatibility issue I also tried from a Linux environment on WSL (Ubuntu) and get the same error.

**Comment by devinshoemaker** [comment]
What version of Node and Nx are you using?

**Comment by sdunnin** [comment]
Sorry, should have provided that.

Node 10.16.0
Nx 9.6.0

**Comment by devinshoemaker** [comment]
Not a problem. Is there a reason you're running an outdated version of Node? I would try the latest version of Node 12 as that's the latest LTS and see if that resolves your issue.

**Comment by sdunnin** [comment]
The only reason for that version is it matches our deploy environment. I checked with the other dev and he is running 10.16.1

**Comment by sdunnin** [comment]
So I updated my node to 10.16.1 to match the other dev but it gave me no love :-(  Have to presume some sort of platform difference which is strange.

Unfortunately we have a deploy environment that limits us to Node 10 for now.

**Comment by Neurogitmeister** [comment]
Hey, coincidentially our team was launching an oinic-react app project and today it was the Windows 10 dev environment testing day. Came across the same error using:
Node 12.18.3
npm 6.14.6
capacitor 2.4.0

Looking at the error i realised that Windows 10 is trying to launch bash script, which it isn't supposed to read.
In /node_modules/.bin/ there's also cap.cmd which is written in CMD language for Windows platforms which is supposed to be used in this case but it doesn't.

So i looked into your @nxtend/capacitor module and found the following:
\node_modules@nxtend\capacitor\src\utils\capacitor-command.js

```javascript
child_process_1.execSync(`node ${context.workspaceRoot}/node_modules/.bin/cap ${command} ${platform}`, { cwd: path_1.join(context.workspaceRoot, projectRoot) });
```
So it looks like that even for windows it is trying to launch the bash script 'cap' from bin.

I solved this issue by adding the cross-platform npm command `npx cap` that is able to locate the right script for the platform by itself so it looks lie this:

```javascript
child_process_1.execSync(\`npx cap ${command} ${platform}\`, { cwd: path_1.join(context.workspaceRoot, projectRoot) });
```

The synced project was able to open in Android Studio on Windows 10 and build with no errors.
I'm not able to test this on iOS but currently heading to Ubuntu 20.04 to confirm the validity of this change.

I don't know if it is the best solution out there, but it makes some sense ;)

**Comment by Neurogitmeister** [comment]
It runs and syncs perfectly fine on Ubuntu 20.04 aswell with this change. Just like it was working on Ubuntu before the change - changes are getting synced and loaded into the IDE automatically.

**Comment by devinshoemaker** [comment]
Thanks for the information @sdunnin and @Neurogitmeister. I think the change @Neurogitmeister proposed makes sense and shouldn't be an issue. I am starting work on site major releases for the Ionic React and Capacitor, but I will try and work the change in for a minor/patch release.

**Comment by devinshoemaker** [comment]
@Neurogitmeister I am testing out your changes but I have run into a small issue. I am currently testing this on macOS, but it seems `npx cap` requires `node_modules/` to be installed into the application folder. Did you have to do this in order to get your example to work?

This is something that I can work around, but I am working on some major changes to the Capacitor and Ionic React plugin so it may be better to wait for a fix for this until then.

**Comment by Neurogitmeister** [comment]
@devinshoemaker thanks for looking into my solution, but I also stumbled upon an error myself now.
The solution seems to only work if you run it within `npx` command that uses local `node_modules` folder like this:
`npx nx run <project-name>:sync --platform <platform>`
> By default, npx will check whether *command* exists in $PATH, or in the local project binaries, and execute that. If <command> is not found, it will be installed prior to execution.

Running this from global scope without `npx` gives an error about it trying to install npx and failing. Forgot to try using that, actually.

About your question: 
if you mean `node_modules/` in the root of the project then yes, if you mean `node_modules/` in capacitor project folder, then no, I didn't have to move it or copy it somewhere else.

**Comment by sdunnin** [comment]
I hacked in the great suggestion by @Neurogitmeister into capacitor-command.js in my node_modules folder.

Unfortunately, it just returns an unhelpful command failed message. Is there a way to get more verbose output?
```
PS C:\git\ONE\nevco-one> yarn nx run controller-cap:sync --platform android
yarn run v1.16.0
$ nx run controller-cap:sync --platform android

> ng run controller-cap:sync --platform=android 
error Command failed with exit code 1.
```
I verified that `npx cap` does run from the command line to rule that out
```
PS C:\git\ONE\nevco-one> npx cap -V
2.4.0
```

**Comment by sdunnin** [comment]
Update: running nx from npx as noted seems to have worked for me.

**Comment by Neurogitmeister** [comment]
I think it is worth noting that removing the `node` from that equation completely solves the issue on Windows 10.
So, if we just remove the `node` command from the line and bypass the node, the cap binary runs fine with whether `npx nx` or `nx`.
Again, heading to test this on Ubuntu.

**Comment by Neurogitmeister** [comment]
So finally there's working, tested and least invasive solution for both `nx` and `npx nx` and for both *Windows 10* and *Ubuntu 20.04* found by me:

node_modules\\@nxtend\capacitor\src\utils\capacitor-command.js:

removing `node` from the line:
```javascript
child_process_1.execSync(`node ${context.workspaceRoot}/node_modules/.bin/cap ${command} ${platform}`, { cwd: path_1.join(context.workspaceRoot, projectRoot) });
```

Executes normally, functionality proven to be working by me in Android Studio 4.4.
@devinshoemaker

**Comment by devinshoemaker** [comment]
Thanks for all of the information everyone. I'll be testing all of this heavily on all platforms ahead of the v2 release. I'll use this ticket for tracking purposes as I work on that.

**Comment by Neurogitmeister** [comment]
Glad i found the solution before i gave up on fixing this :D
I'm almost positive i tried it (removing 'node') as i was searching through stackoverflow with this error message, but it somehow failed to work the first time, maybe i was still using 'cap.cmd' in path 🤔 
Hope this will make Windows devs happier one day, not everything should be done with WSL! 😄

**Comment by devinshoemaker** [comment]
I am working on an upcoming change that actually adds a `package.json` and `node_modules/` which will hopefully solve the `npx` issue.

**Comment by Neurogitmeister** [comment]
This will be more invasive but it's your call. IMO removing node should be the right solution as i've rushed through two-three tutorials on executing bash scripts on nodeJS and it involves `child_process` and it's `exec` method called without 'node' inside, so this should be the only issue. 'npx cap` callded from inside could be still a very rushed solution as i had no expertise on how it would work. But again, it's your call and wish you the best of luck with the project :)

**Comment by Neurogitmeister** [comment]
This will be more invasive but it's your call. IMO removing `node` from command should be the right solution as i've rushed through two-three tutorials on executing bash scripts on nodeJS and it involves `child_process` and it's `exec` method called without `node` inside, so this should be the only issue. `npx cap` called from inside could be still a very rushed solution as i had no expertise on how it would work. But again, it's your call and wish you the best of luck with the project :)

**Comment by devinshoemaker** [comment]
@Neurogitmeister @sdunnin `2.0.0-beta.1` has been published, would either of you mind testing it out? I would recommend running `nx migrate @nxtend/capacitor@2.0.0-beta.1` and following the instructions. There's a few changes to the way Capacitor projects will work in v2.

**Comment by sdunnin** [comment]
Any idea when 2.0.0 will be general release @devinshoemaker?

**Comment by devinshoemaker** [comment]
I hate to say it, but when it's ready. 😄  This is a night and weekend project so it can be hard for me to get a good estimate, but I think I'm done with the major changes for this plugin so now it's down to updating documentation and some dependencies. So hopefully not long!
