### ISSUE TITLE
doc(ionic-angular) add in the plugins list

### ISSUE THREAD

**Issue by pegaltier** [nxtend-team/nxtend#305]
at the moment ionic-angular is not in the README plugin's list

**Comment by devinshoemaker** [comment]
Thanks! I actually did forget to submit a PR for this. Will get to it ASAP.

**Comment by devinshoemaker** [comment]
Just got this up as a PR. 
https://github.com/nrwl/nx/pull/4189

**Comment by pegaltier** [comment]
Oh right, i was talking about the local README file: i opened a PR for this: https://github.com/nxtend-team/nxtend/pull/313

**Comment by devinshoemaker** [comment]
Ah! I skimmed the issue too quickly. Thanks for the PR! It also reminded me that this needed to be updated as well: https://github.com/nxtend-team/nxtend/pull/314
