### ISSUE TITLE
project migration angular to ionic

### ISSUE THREAD

**Issue by nhhockeyplayer** [nxtend-team/nxtend#308]
I was operating an earlier angular project and workspace

I deleted it angular project and installed a new project using this schematic for ionic

but the package.json was missing cap.copy and other commands

can a switch or auto-migration sync check be performed for ionic projects so that we can have our project up to snuff for what its suppose to have for commands and such

here are my steps to reproduce

```
npx create-nx-workspace@latest energy
cd energy
yarn add -D --exact @nxtend/ionic-angular
nx generate @nxtend/ionic-angular:init
nx generate @nxtend/ionic-angular:application e2-ask 
nx build e2-ask 
nx serve e2-ask 
npm run build.ionic.e2ask
npm run prepare.ionic.e2ask
npm run sync.ionic.e2ask
npm run clean.ionic.e2ask
```

**Comment by devinshoemaker** [comment]
Currently, the add, copy, sync, and open Capacitor commands are supported by this plugin. These are executed in this fashion:

`nx run e2-ask:add:ios`

I need to improve the documentation on this, but that should work with a newly generated project.

**Comment by nhhockeyplayer** [comment]
Is there a windows platform other than ios/android?

typically I qualify as much UI/material prior to taking direct traction on ios or android

**Comment by nhhockeyplayer** [comment]
Also wondering how to configure the following

```
Add a network security config
New file in project: resources/android/xml/network_security_config.xml

<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
  <!-- Set application-wide security config -->
  <base-config cleartextTrafficPermitted="true"/>
</network-security-config>
```

**Comment by nhhockeyplayer** [comment]
Is it possible to have a schematic to build the apk?

that would be the frosting on the cake

**Comment by devinshoemaker** [comment]
> Is there a windows platform other than ios/android?
> 
> typically I qualify as much UI/material prior to taking direct traction on ios or android

Do you mean a platform like Electron to run apps on the desktop OS?

> Also wondering how to configure the following
> 
> ```
> Add a network security config
> New file in project: resources/android/xml/network_security_config.xml
> 
> <?xml version="1.0" encoding="utf-8"?>
> <network-security-config>
>   
>   <base-config cleartextTrafficPermitted="true"/>
> </network-security-config>
> ```

Is this for a Capacitor plugin?

> Is it possible to have a schematic to build the apk?
> 
> that would be the frosting on the cake

This plugin will only support commands that are built into the Capacitor CLI, and I don't believe that is available yet.
https://github.com/ionic-team/capacitor/issues/324

**Comment by devinshoemaker** [comment]
I'll be closing this issue for now. Feel free to reply, or create a new issue if you still have problems.
