### ISSUE TITLE
Generating ionic-angular app with Jest and Cypress

### ISSUE THREAD

**Issue by joelmuskwe** [nxtend-team/nxtend#333]
Is it possible to generate up configured with Jest and Cypress

**Comment by devinshoemaker** [comment]
Not currently directly through the plugin. However, this plugin just leverages other default plugins, so you could always generate an app with `--unitTestRunner none` and then run `nx g @nrwl/jest:jest-project` to configure Jest for your project. I'll try and add this to the docs soon.
