### ISSUE TITLE
error: Builder is not a builder

### ISSUE THREAD

**Issue by ravi155** [nxtend-team/nxtend#335]
Going through getting started in @nxtend/ionic-angular

nx build mobile-app  built app ok

then adding platform
nx run my-app:add:ios i get "Builder is not a builder" red error, nothing more.

What am i doing wrong?

**Comment by hoisel** [comment]
The same issue!

**Comment by devinshoemaker** [comment]
Thanks for reporting the issue. I have confirmed it on my end and will work on a fix.

**Comment by devinshoemaker** [comment]
@ravi155 and @hoisel can you confirm if you are on Nx 11 or not? I seem to only see this issue on Nx 11+.  I am currently working on Nx 11 support, so if that's the case, then hopefully everything will be resolved soon. I also plan to more explicitly set the recommended Nx version in the plugins `package.json` so users should get alerted of this.

**Comment by ravi155** [comment]
@devinshoemaker i have 10.4.4

**Comment by ravi155** [comment]
@devinshoemaker my mistake - I checked other repo. Yes it is 11.0.4

**Comment by devinshoemaker** [comment]
Okay makes sense. I'm guessing there is some breaking change in the Nx plugin toolkit with Nx 11. It sounds like this stuff should be a bit more stable and reliable to use going forward so hopefully there's not another issue like this. I'll keep this issue open until I get the next version of this plugin released that's based on Nx 11.

**Comment by hoisel** [comment]
@devinshoemaker  I have 11.0.8. Thanks you for your quick reply!

**Comment by devinshoemaker** [comment]
Thanks! I don't have the ETA for the plugin update but I am aggressively working on it when I can. Hopefully I can wrap things up within the next week or two.

**Comment by devinshoemaker** [comment]
Nx 11.0.19 fixes this issue, so if you update you should be able to get past this error message. There are still a couple of issues with Nx 11, such as the `--style css` option being broken, but this will all be fixed with the upcoming Nxtend update. If you still have issues, feel free to reply and I will reopen this issue.
