### ISSUE TITLE
Invalid format version detected - Expected:[ 1 ] Found: [ 2 ] when Adding native platforms

### ISSUE THREAD

**Issue by mhar-andal** [nxtend-team/nxtend#361]
My [test app](https://github.com/mhar-andal/nx-capacitor-test ) will throw this error

`Invalid format version detected - Expected:[ 1 ] Found: [ 2 ] `

when running `nx run mobile-app:add --platform ios` or `nx run mobile-app:add:ios`.

I've followed the section **Generate Ionic React App with Capacitor** in this [blog](https://dev.to/devinshoemaker/build-cross-platform-applications-in-a-monorepo-with-nx-ionic-and-capacitor-6f8) but can't seem to figure out why I'm running into this error.

I've tried researching this error, it seems specific to angular? I'm coming from react and am very new to angular.

**Comment by devinshoemaker** [comment]
Interesting, I haven't seen this error before and I'm having trouble pinpointing exactly where it's coming from. That being said, the Nxtend plugins currently don't support Nx 11 and have some issues, so it's likely related to that. I'm currently in the process of updating all the plugins to support Nx 11 and will hopefully have everything ready over the next couple weeks. If you want to try the plugins out in the meantime, feel free to set up a new project using Nx 10 with `npx create-nx-workspace@10`.

**Comment by devinshoemaker** [comment]
@mhar-andal Nxtend 11 has been released. Can you please update and test your issue again?

**Comment by mhar-andal** [comment]
It is working great now, thank you for the speedy release :)

**Comment by devinshoemaker** [comment]
Awesome, glad to hear it!
