### ISSUE TITLE
Create own Capacitor plugin

### ISSUE THREAD

**Issue by jase88** [nxtend-team/nxtend#392]
Hey there, 

Sorry, this is not a real issue but rather a question. 

Is it possible to create own Capacitor plugins within my nx workspace with this plugin?

**Comment by devinshoemaker** [comment]
Sadly you cannot. I am not experienced in creating Capacitor plugin myself, but you may be able to do that with a standard `nx g @nrwl/node:lib` schematic.

**Comment by jase88** [comment]
Managed to get it working with `npx @capacitor/cli plugin:generate` and manually adjusting a nx node lib - like suggested.

Real pain was to define package.json and link it manually as npm local dependency to the top level package.json. Was a bit against nx philosophys. Hopefully the Capacitor 3 API gets better regarding own plugins.
