### ISSUE TITLE
tslint deprecated in favor of eslint

### ISSUE THREAD

**Issue by troywweber7** [nxtend-team/nxtend#393]
TSlint has been deprecated in favor of ESlint. Are there any plans to switch `nx generate @nxtend/ionic-angular:application` over to use eslint? Or does anyone know about any workarounds?

**Comment by devinshoemaker** [comment]
Hey there, thanks for bringing this up. When I first tried to implement Dealing for this plugin there was a bug with Nx. I actually think this is fixed now, so I should look into this again. I'm not an expert in TSLint to ESLint migrations, so that will be the tricky part to figure out.

**Comment by troywweber7** [comment]
@devinshoemaker I'm not an expert either, actually. I do know that eslint uses a plug-in called typescript-eslint or something like that. Also, I think nrwl, since Nx10 and Angular 10, may have adjusted and might serve as an example.

**Comment by devinshoemaker** [comment]
It doesn't look like the upgrade to Nx 11 provided a migration from TSLint to ESLint for Angular applications. It should be trivial for me to default new applications to using ESLint, but I may have to leave the conversion process to the user.

**Comment by troywweber7** [comment]
Sweet! Thanks for this project, btw. It's nice to have an option that fits within Nx when learning about mobile development for the first time.

**Comment by devinshoemaker** [comment]
Awesome, I appreciate it! By the way, a TSLint to ESLint migration is on the Nx roadmap: https://github.com/nrwl/nx/issues/4492

**Comment by troywweber7** [comment]
@devinshoemaker so if your scripts depend on the nx scripts, then there probably isn't much you would need to do, right?

**Comment by devinshoemaker** [comment]
Correct. The Ionic Angular applications that are generated are extended from the Nx Angular apps, so the migration should run just fine once it's released. I imagine it will be an opt-in type thing.

**Comment by troywweber7** [comment]
Sweet. Do we close this or is it still useful to the repo management?

**Comment by devinshoemaker** [comment]
I think it's worth closing for now. Once the migration is released, if you have problems then feel free to open another issue.
