### ISSUE TITLE
Capacitor commands fail

### ISSUE THREAD

**Issue by phal0r** [nxtend-team/nxtend#408]
I set up a nx workspace with the latest version, added a simple react app and a simple react lib. Now I wanted to add Capacitor for the app using the following commands:

npm install --save-dev @nxtend/capacitor

npx nx build test-app

npx nx generate @nxtend/capacitor:init

npx nx generate @nxtend/capacitor:capacitor-project --project test-app

The last command fails with `Required property 'npmClient' is missing`

Any ideas, where this should be set?

**Comment by devinshoemaker** [comment]
Ah, this is another property to pass into the command. At one point I updated this and added a required property but forgot to update the documentation. I'll get that fixed soon. This is what you should run `npx nx generate @nxtend/capacitor:capacitor-project --project test-app --npmClient npm` or replace npm with yarn if you'd prefer.

**Comment by phal0r** [comment]
Thanks, that works indeed. I was trying to set it in different json files without success, so I was quite lost.

Do you want to take this issue as reference for updating the docs? Otherwise it can be closed.

**Comment by devinshoemaker** [comment]
Sorry for the delay. We can leave it open for now, I plan to address this soon.
