### ISSUE TITLE
Plan to support Eslint

### ISSUE THREAD

**Issue by Frankitch** [nxtend-team/nxtend#413]
As eslint is the linter recommended by Nrwl, is there a plan to generate apps with eslint ?

**Comment by devinshoemaker** [comment]
Yes this is definitely on the roadmap. I had some initial issues with getting ESLint to work with the `ionic-angular` plugin, but I plan to revisit it soon.

**Comment by beeman** [comment]
I would love to see this too! Happy to jump on board getting this in @devinshoemaker :)

**Comment by devinshoemaker** [comment]
Well hello @beeman ! I have some time today to take another stab at this. I don't expect it to be too much work, I'll just need to update each of the starter templates for new linting errors. I'll reach out if I run into issues!

**Comment by devinshoemaker** [comment]
@Frankitch @beeman I have a PR up and testing has gone well. I'll probably merge it today, but I'm planning a larger release so I might wait on that to release this feature.

**Comment by Frankitch** [comment]
Awesome!
