### ISSUE TITLE
environment variable ?

### ISSUE THREAD

**Issue by vtrphan** [nxtend-team/nxtend#453]
I use nxtend with Nx to generate a Ionic/Capacitor project but somehow i can't use .env environment variables. They're always undefined. I read that ionic uses Create React App under the hood, so it should work with REACT_APP_... variables. But i see no react-scripts dependency. How can i use environment variables with React?

**Comment by devinshoemaker** [comment]
This is supported by Nx directly. You should be able to add a variable in a `.env` file but it has to start with `NX_*` instead.

https://nx.dev/latest/react/guides/environment-variables#environment-variables
