### ISSUE TITLE
Not syncing capacitor plugins if they are in the root package.json

### ISSUE THREAD

**Issue by paulburz** [nxtend-team/nxtend#469]
Hi I was trying to install and use https://github.com/capacitor-community/barcode-scanner
And if the package was installed in the root package.json the sync  Command would not find any capacitor Plugins
If I move the plugin into the App package.json it works.
I don't know if this is intended

Repro Steps:

1.    Follow the steps from the https://github.com/capacitor-community/barcode-scanner
2.    And see if the Podfile, capacitor.build.gradle, capacitor.settings.gradle is updated are the Plugin imports
3.    Create ionic project without nx and nxtend and do the same, the Podfile, capacitor.build.gradle, capacitor.settings.gradle should be updated with the plugin

**Comment by devinshoemaker** [comment]
Hey there, yes this is a limitation with the Capacitor CLI that is used under the hood. In my experience, the best results are if you put the plugin in both the root and project-level package.json. Feel free to reopen this if you have any other issues.

https://nxtend.dev/docs/capacitor/getting-started#adding-capacitor-plugins

**Comment by paulburz** [comment]
Hello, sorry for not paying attention more closely to the docs. 
Thanks for creating this project it's really useful and a great one :)

**Comment by zirlman** [comment]
@paulburz did you manage to install this plugin correctly?  If so, could you please elaborate on what you have done? I'm really having problems with managing this plugin to work https://github.com/capacitor-community/barcode-scanner/issues/38

**Comment by tafelnl** [comment]
@paulburz Did you try running `npx cap sync` from both root and project-level?

**Comment by paulburz** [comment]
@zirlman @tafelnl Hi after putting the dependency for the capacitor plugin in both package json files (the root one and the project-specific one) I just ran **nx run {app-name}:sync:{platform}** and they synced and followed the instruction from the plugin page to make it work on Android.

**Comment by paulburz** [comment]
@zirlman @tafelnl You can also run capacitor specific scripts like ```npx cap sync``` but you need to be in the app folder
