### ISSUE TITLE
Capacitory 3 support

### ISSUE THREAD

**Issue by andreastoermer** [nxtend-team/nxtend#470]
Hello,

for a project we have been using NX and Ionic for quite some time and accordingly have built an environment with both, which however is still based on Capacitor 2.4.7.

Now that the official release for the 3 variant of Capacitor has been announced, I wanted to ask about the support of @nxtend/capacitor in this regard, since I could not find anything.

Are there any problems or is it safe to update to the 3 version?

With best regards

Translated with www.DeepL.com/Translator (free version)

**Comment by devinshoemaker** [comment]
Hello, I am currently working on a large update to the Nxtend plugins to add official support for Nx 12, Angular 12, Capacitor 3, and so on. This is a rather large effort and I am not sure when the update will be released, but I see no problem with trying to upgrade to Capacitor 3 manually. Feel free to report back if you have success or if you have problems.

**Comment by sergiocarneiro** [comment]
@devinshoemaker Thank you for your tireless support to this project 👏

Looking forward to the Nxtend 12!

**Comment by andreastoermer** [comment]
Capacitor 3 works very good with the current version. i will close this ticket. thanks @devinshoemaker
