### ISSUE TITLE
Support Cordova

### ISSUE THREAD

**Issue by jdnichollsc** [nxtend-team/nxtend#493]
Hello folks, thanks for this project!

I want to request support for Cordova projects with Ionic, how can I help to do that?

Thanks again for your collaboration <3

**Comment by devinshoemaker** [comment]
Hi, I appreciate the offer to help add Cordova support to these plugins, this is not something I'm interested in bringing into this project. Cordova would be much harder to maintain than Capacitor, and I do not have the capacity to continue that maintenance. If you require Cordova for development and cannot use Capacitor then I would recommend looking into the Nrwl `run-commands` executor. You can configure Cordova manually and use that to create custom commands for the Nx CLI.
