### ISSUE TITLE
Command failed: npx cap add android

### ISSUE THREAD

**Issue by muuvmuuv** [nxtend-team/nxtend#494]
Getting this error after running ` nx run entergon:add:android`. I have installed the capacitor CLI globally and locally in my project. The verbose output:

```
......
found 6 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
[error] The Capacitor CLI needs to run at the root of an npm package.
        Make sure you have a package.json file in the directory where you run the Capacitor CLI.
        More info: https://docs.npmjs.com/cli/init
ERROR: Something went wrong in @nrwl/run-commands - Command failed: npx cap add android
Error: ERROR: Something went wrong in @nrwl/run-commands - Command failed: npx cap add android
    at C:\Users\marvinheilemann\Development\entergon\node_modules\@nrwl\workspace\src\executors\run-commands\run-commands.impl.js:53:19
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\marvinheilemann\Development\entergon\node_modules\tslib\tslib.js:115:69)
```

Do I need to add a package.json in the projects folder? I followed this guide here but none got generated during that setup: https://ionicframework.com/blog/ionic-angular-monorepos-with-nx/

**Comment by muuvmuuv** [comment]
Fixed by creating an empty package.json. I don't know what went wrong. I am on Windows 10.

**Comment by kinggolf** [comment]
Thank you @muuvmuuv - I was getting this error `could not determine executable to run` when running the same command as you. There actually was a package.json file in my project where I was trying to add ios and android platforms, but did not know why so I deleted it. Replacing it fixed my problem.

**Comment by devinshoemaker** [comment]
Yeah this is a limitation of the Capacitor CLI. It requires a `package.json` in the directory where the Capacitor command is executed, and under the hood my plugin executes Capacitor commands from the applications directory.
