### ISSUE TITLE
"Init" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.

### ISSUE THREAD

**Issue by VictorienTardif** [nxtend-team/nxtend#516]
I'm trying to add the `@nxtend/capacitor` plugin to an existing `nx` workspace but after installing the plugin with `nx add @nxtend/capacitor`, when I run `nx generate @nxtend/capacitor:init` I get the following error:

```
"Init" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
```

**Comment by devinshoemaker** [comment]
Hi, thanks! Yeah I'm aware of this issue, I think something was changed in Nx 12 that made it no longer compatible with my plugin. I have been working hard the last few months to rewrite these plugins for Nx 12 compatibility among other things. I'm hoping I can start rolling out updates within the next couple weeks.
