### ISSUE TITLE
chore(firebase): retire firebase plugin

### ISSUE THREAD

**Issue by devinshoemaker** [nxtend-team/nxtend#539]
- [ ] update docs
- [ ] remove plugin
- [ ] update GitHub action

**Comment by sbuys** [comment]
Thanks for your work on nxtend! Sad that you're removing the firebase plugin. Would be much appreciated if you could include some pointers for integrating firebase now that this is going away.

**Comment by t-mish** [comment]
Just found this plugin, and so sad news 😥

**Comment by devinshoemaker** [comment]
I appreciate the love! Yeah sadly I don't have as much time to work on these plugins, so this one has to go in favor of the Ionic ones. When I release the rest of the plugins I will include a blog post on how to implement what this plugin does in a manual way. It's actually very simple using the run-commands executor. Apologies to everyone using this, hopefully someone will carry the torch forward. All my Firebase related code is free game if anyone is looking to make their own plugin.

**Comment by devinshoemaker** [comment]
@t-mish @sbuys I reversed my decision to retire this plugin. v12.0.0 is now out.
