### ISSUE TITLE
Firebase not working with capacitor for mobile app

### ISSUE THREAD

**Issue by ben-kn-app** [nxtend-team/nxtend#545]
Dear, 

I am maintaining 18 ionic firebase cordova apps in different repo's with submodules. I love the 'uncomplexity' that nx and your nxtend could bring! Thanks for the good and hard work!

Currently I cannot find a way to get firebase and capacitor to work together.  I can imagine that you as a maintainer are using capacitor and firebase in a mobile app together? How did you get it to work? 

I am using
```
"@nxtend/capacitor": "^12.0.0-beta.1",
"@nxtend/firebase": "^11.1.2",
"@nxtend/ionic-angular": "^12.0.0-beta.1",
"@capacitor/cli": "^3.2.5",
"@nrwl/cli": "12.10.0",
"@nrwl/cypress": "12.10.0",
"@nrwl/eslint-plugin-nx": "12.10.0",
"@nrwl/jest": "12.10.0",
"@nrwl/linter": "12.10.0",
"@nrwl/react": "^12.0.0",
"@nrwl/tao": "12.10.0",
"@nrwl/workspace": "12.10.0",
"@ionic/angular": "^5.8.3",
"cordova-plugin-firebasex": "^13.0.1",
```

The roadblock I'm running into is that the used plugin cordova-plugin-firebasex is not designed/supported for capacitor, examples: [issue](https://github.com/dpa99c/cordova-plugin-firebasex/issues/610), [issue](https://github.com/dpa99c/cordova-plugin-firebasex/issues/204) and [issue](https://github.com/dpa99c/cordova-plugin-firebasex/issues/357))

This while capacitor claims to be backward compatible for cordova plugins.

I get it compiling, building and even functioning on an ios device, the database is working, but I can't get the firebase analytics nor the notifications to work (that were working previously on cordova). Getting console errors like: 
`8.4.0 - <AppMeasurement>[I-ACS025018] Event not logged. Call +[FIRApp configure]: appLoaded`

For android I can't even get it to compile and getting errors described in this [issue](https://github.com/ionic-team/capacitor/issues/3376). Perhaps if I follow the thread in the description I can find a manual workaround. 

Another workaround would be to NOT use capacitor but cordova, which would solve the issue for me and would allow me to make the step to migrating to nx smaller. But currently there is no support for cordova in nxtend and is not on the roadmap, [source](https://github.com/nxtend-team/nxtend/issues/493). 

I'm not a fan of workarounds, especially not if I need to manually do it all 18 apps. But it could be a start to remove the roadblock to start migrating to nx. 

To summerize how did you get firebase to work on mobile with capacitor? 
As nxtend is build especially for ionic and firebase, I can't imagine I am the only one going to run into this problem. So hopefully this issue could guide some new users of nxtend.

**Comment by ben-kn-app** [comment]
After a week of this roadblock I just solved it a few hours after creating this issue. I hate when that happens. But I am gonna leave this issue here so maybe other users don't need this week of agonizing grinding.

To get it running I had to make 2 changes: 
1. From the firebase SDK instructions I added  FirebaseApp.configure() to App/AppDelegate.swift and added the GoogleService-Info.plist to the App directory. The exact instruction you can find in your firebase project -> Project Settings -> IOS App and show instructions for SDK
FYI: I did NOT add the firebase to the podfile.
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        FirebaseApp.configure()
        
        return true
    }
```
2. Add the GoogleService-Info.plist ALSO to folder (outside of xcode) /ios/capacitor-cordova-ios-plugins/resources/

**Comment by devinshoemaker** [comment]
Hey @ben-kn-app , thank you for your compliments and for leaving your solution! I would like to let you know that I am retiring the Firebase plugin and won't have any future releases. I'm finishing up the major updates to the rest of my plugins and my blog post will feature a migration guide from my Firebase plugin to using Nrwl's `run-commands` executor. Sad to say it won't be quite as convenient to set up a new app, but once you migrate it should work just as smoothly as with my plugin.

**Comment by devinshoemaker** [comment]
Surprise @ben-kn-app, `@nxtend/firebase` 12.0.0 has been released. I changed my mind on retiring the plugin and v12.0.0 has been released.

**Comment by ben-kn-app** [comment]
Suberb! Thanks for your continued efforts, will check it out right now!
