### ISSUE TITLE
firebase unable to create project with nx 13

### ISSUE THREAD

**Issue by pxPP** [nxtend-team/nxtend#580]
After I run the `ng add @nxtend/firebase` command I get the error message: 

`Unable to resolve @nxtend/firebase:ng-add.
Cannot find generator`

**Comment by samratarmas** [comment]
> https://github.com/nxtend-team/nxtend/issues/584#issuecomment-1001802617

**Comment by devinshoemaker** [comment]
`ng add` isn't necessary with this plugin, you can simply add it to your dev dependencies and begin using it.

**Comment by devinshoemaker** [comment]
Let me know if you have any issues, otherwise, I will close this issue in a few days.
