### ISSUE TITLE
Add Capacitor support to existing project

### ISSUE THREAD

**Issue by kunjee17** [nxtend-team/nxtend#598]
Hi, 

Is it possible to add angular/capacitor support to existing project? I can't find any documentation about it. 

And thanks for nice plugin. it makes things seriously easier.

**Comment by devinshoemaker** [comment]
Yup! You can add Capacitor to most single page apps.
https://nxtend.dev/docs/capacitor/getting-started#add-capacitor-to-existing-project

Let me know if this is not what you're looking for, otherwise I'll close this issue in a few days.
