### ISSUE TITLE
A proposal to add an Electron platform with a plugin capacitor-community/electron

### ISSUE THREAD

**Issue by FathiGuemri** [nxtend-team/nxtend#611]
I have a suggestion to add Electron platform to your project , 

plugin [@Capacitor-Community-Electron](https://capacitor-community.github.io/electron/)  to generate an electron project available for Deploy your Capacitor apps to Linux, Mac, and Windows desktops, with the Electron platform 

I tried in my workspace with nxtend and it was pretty cool, but I had some problems and found solutions that are not workable
In the original nxtend files in node_module I modified a file `add-project.js`

I added the [@capacitor-community/electron](https://capacitor-community.github.io/electron/) platform in the platforms array 

`const platforms = ['ios', 'android', '@capacitor-community/electron'];`

I had trouble recognizing the `@capacitor-community/electron`  library from the node_modules file when running the `add` command 

I just created the node_modules folder in the root of myapp and put a copy of `@capacitor-community/electron`  library in it 

all the commands `add`  `copy`  `open` and `sync` is working  Except `run` command and this is a problem

```
Specify the project name and the target (e.g., nx run proj:build)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command yarn nx run test --configuration=@capacitor-community/electron" terminated with exit code: 1.
```

That's it, and thanks

**Comment by revalebe** [comment]
@FathiGuemri did you found a solution?
